- hosts: web
  tasks:
  - name: Selinex perm dissable
    selinux: 
      state: disabled

  - name: install python36
    include_tasks: py36-v2.yml  

  - name: Install pip
    include_tasks: pipgit-v2.yml

  - name: Clone and move
    include_tasks: gitCloneAndMove-v2.yml

  - name: Run app!
    args:
      chdir: /home/centos/Flaskex
    shell: 'nohup python app.py &'

    # nohup will allow to continue run app while terminal would be disconnected
    # & will run app in background mode
    # netstat -plnt command will allow to check used ports on app

      
    
