- hosts: web 
  vars_files:
  - vars.yml
  tasks:
  - name: Debug
    debug:
      msg: "Hello {{ param1 }}!"


# Variable presedence
# apb -e "param1=Peter" debug.yml -> # it will overide <Class> value with <Peter>
