- hosts: web
  tasks:
  - selinux:
      state: disabled
  - name: permenantly disabled
    lineinfile:
      path: /etc/sysconfig/selinux
      regexp: '^SELINUX=enforcing'
      line: 'SELINUX=disabled'
   
    
    
      

