- hosts: web
  tasks:
  - name: Install apache
    include_tasks: "{{ ansible_os_family }}Apache.yml"
  - name: Download Template
    include_tasks: "{{ ansible_os_family }}downloadTemplate.yml"
  - name: Change ownership to apache
    shell: sudo chown -R apache:apache /var/www/html
  - name: Disable SELinux
    include_tasks: "{{ ansible_os_family }}disableSelinux.yml"
    


    
